# ------ training parameters ------ 
num_epochs: !!int 50
batch_size: !!int 256
learning_rate: !!float 0.001 #0.001
lambda: !!float 1.0 # ID regularization parameter
beta: !!float 0.3 # distance regularization parameter
gradclip: !!float 1.0
lr_decay: !!float 0.5
lr_decay_step: !!int 5
## value network parameters
num_value_epochs: !!int 200
value_net_lr: !!float 0.001 # 0.001
value_net_lr_decay_step: !!int 5
value_net_lr_decay: !!float 0.5
train_dynamics: !!bool True
train_value: !!bool True


# ------  model parameters ------ 
hidden_dim: !!int 8


# ------  data parameters ------ 
num_steps: !!int 8
traj_length: !!int 50
num_trajectories: !!int 1000


# ------ environment parameters ------ 
env_name: !!str Pendulum-v1
sample_trajectories: !!bool True

Q_weight: !!float 1
R_weight: !!float 0.01


# ------  evaluation parameters ------
eval_T: !!int 200 # number of time steps to evaluate
eval_episodes: !!int 100 # number of times to evaluate
render: !!bool False
